dfinity/public-workflows

.github/workflows/check_cla.yml, reusable_workflows/check_membership/check_membership/action.yml
Using `merge_group` leads to strange behavior, as the workflow isn't able to recognize who the author is when run on a merge queue, therefore labeling the person as an external contributor. However, we still need the `merge_group` to trigger the workflow, otherwise the ruleset will fail. Therefore we trigger the workflow but still skip it from being executed.
=> dont run if triggered by merge queue

.github/workflows/check_cla.yml
I tested this out and the behavior does not match up with what is described [here](https://github.com/orgs/community/discussions/58673). The `github-merge-queue[bot]` does not show up as the actor for a merge queue. 
For merge queues:
`github.actor`: person who created PR
`github.event.sender.login`: person who created the PR
`github.event.pull_request.user.login`: empty for merge queue
It looks like my original idea to just skip the merge group is the best option.
=> disable workflow for merge queue

.github/workflows/check_cla.yml
Apparently `github.actor` is just the last person that triggered the event, not the author of the PR.
=> change actor to PR author

reusable_workflows/check_membership/check_membership.py, reusable_workflows/tests/test_membership.py, setup.cfg
The old bot was causing some issues, so I'd like to move to repos to this new workflow. The only problems is that forked repositories don't work with rulesets because `pull_request_target` is not supported. This change classifies any github authentication error as an external contributor and the PR will be automatically closed. This is only until `pull_request_target` is supported by rulesets.
=> dont raise exception

reusable_workflows/check_membership/check_membership.py, reusable_workflows/tests/test_membership.py, setup.cfg
Now that `pull_request_target` is available we can use secrets.
Reverts dfinity/public-workflows#22
=> Revert "dont raise exception"

.github/workflows/check_cla_ruleset.yml
Tested it out and it fails: https://github.com/dfinity/test-compliant-repository-public/actions/runs/6705207237/job/18219172484
Test if merge_group can be removed completely
=> Remove merge_group trigger on workflow

.github/workflows/check_issue_signed.yml
It makes more sense to have this workflow stored in public-workflows and create a ruleset to only run it on the cla repository. That way all the CLA code will be in one place.
See other PR here: https://github.com/dfinity/cla/pull/403
=> move CLA check signed to public-workflows

reusable_workflows/check_cla/check_cla_pr.py, reusable_workflows/tests/test_cla_pr.py
When we initially launched the workflow we created a new pending label `cla:gh-wf-pending` so that the new bot and old bot wouldn't interfere. Now that we are shutting down the old bot, we need the cla workflow to check for both labels, but assign new issues the `cla:pending` one.
=> Update pending label

.github/workflows/check_cla.yml, reusable_workflows/shared/messages.py
I didn't realize that the closing message is actually defined in the workflow itself. I'm guessing I did it that way because closing the PR programmatically was too complex.
=> fix(IDX): change closing message

.github/workflows/check_cla_dev.yml, .github/workflows/check_cla_ruleset.yml, README.md
Instead of having the ruleset pointing to a specific tag and the code pointing to `main` I'd like to switch it -> now the code will point to the new tag and the ruleset will point to main. This will have two benefits:
1. Only a code change is required and no additional changes to the ruleset
2. I'm hoping it will fix the issue where workflows are blocked because the tag on the ruleset was changed
=> test(IDX): switch from main to tag

.github/workflows/check_cla.yml, .github/workflows/check_cla_signed.yml, .github/workflows/python-setup/action.yml, .github/workflows/python_lint_test.yml, .github/workflows/repo_policies.yml, .github/workflows/repo_policies_ruleset.yml, reusable_workflows/repo_policies/bot_checks/check_bot_approved_files.py
This PR introduces the new ruleset `Repo Policies`. It also makes a small improvement to how python is setup in all workflows.
=> chore(IDX): create workflow for repo policies

.github/workflows/repo_policies.yml, reusable_workflows/repo_policies/bot_checks/check_bot_approved_files.py, reusable_workflows/tests/test_repo_policies.py
There are still some issues with the script which I haven't fully debugged. These changes explicitly fail the script and add more debugging messages.
=> chore(IDX): updates to bot check script

.github/workflows/repo_policies.yml
The difficult part with this workflow is that it needs to execute code from another repo but still run git commands in the current repo. I will try something else out. Unfortunately there's no way to test without merging to main, as the ruleset doesn't seem to work with non-main branches.
=> fix(IDX): try two checkout steps

.github/workflows/check_cla_dev.yml, .github/workflows/python-setup/action.yml, .github/workflows/repo_policies.yml, .github/workflows/repo_policies_ruleset.yml
Work-around to enable multi-repo checkout. 🤞 
Repo Policies Ruleset failing as it is currently pinned to main.
=> fix(IDX): enable multi-repo checkout

.github/workflows/repo_policies.yml, .github/workflows/repo_policies_ruleset.yml, reusable_workflows/repo_policies/bot_checks/check_bot_approved_files.py, reusable_workflows/tests/test_repo_policies.py
Because of the multi-repo checkout step we need to specify which directory the git commands should be run in.
=> fix(IDX): run git commands in a different dir

reusable_workflows/check_cla/check_cla_pr.py, reusable_workflows/tests/test_cla_pr.py
Since migrating the cla workflow from the service account to the GitHub App a permissions error gets triggered when adding the `pending` label to the issue. I've tried to debug, but I haven't been able to replicate the error using my user account - my guess is there's something that is different in how bots get permissions vs users.
Since this is the only problem and setting the `approved` label still works fine I have decided that having the `pending` label is not crucial and I am removing it.
=> fix(IDX): remove pending label

reusable_workflows/check_cla/check_cla_issue.py, reusable_workflows/check_cla/check_cla_pr.py, reusable_workflows/tests/test_cla_issue.py, reusable_workflows/tests/test_cla_pr.py
In trying to debug some CLA issues, I noticed that the logic is very convoluted, so I made some updates. I changed some function names, but the main change is that I removed the step that checks the name of the bot, so we won't run into issues if we need to change the bot that triggers this workflow again.
=> refactor(IDX): update comment logic

.github/workflows/python_lint_test.yml, .gitignore, reusable_workflows/compliance/check_compliance/compliance_checks.py, reusable_workflows/tests/conftest.py, reusable_workflows/tests/test_check_external_contrib.py, reusable_workflows/tests/test_compliance_checks.py, reusable_workflows/tests/test_membership.py, reusable_workflows/tests/test_utils.py
Up until now I have only used unit tests and mocked the github responses. This PR introduces integration tests that use a real github token to make calls to a test repository, here: https://github.com/dfinity/test-compliant-repository-public
The benefits include:
- easier to catch permissions issues
- easier to refactor code
- easier to upgrade `github3` package and be made aware of any breaking changes
=> feat(IDX): introduce integration tests

reusable_workflows/check_cla/check_cla_issue.py, reusable_workflows/check_cla/check_cla_pr.py, reusable_workflows/tests/test_cla_issue.py, reusable_workflows/tests/test_cla_pr.py
This re-adds the change from last week (https://github.com/dfinity/public-workflows/pull/78) but with the correct fix. It also adds integration tests that would catch this failure next time.
=> chore(IDX): update comment logic

.github/workflows/internal_vs_external.yml
The purpose of adding this workflow is to enable separate branch protection rules within the same repo. The logic works as follows:
- `for internal contributors`: keep default level 2 branch protection rules -> with every new push reviews are kept and only one additional review (not by the commit author) is required
- `for external contributors`: implement level 3 branch protection rules via this workflow -> with every new commit all PR reviews are cleared and the PR must be re-approved by all code owners
See the diagram below for the workflow logic:
=> feat(IDX): add internal-external workflow

reusable_workflows/check_membership/check_external_contrib.py, reusable_workflows/tests/test_check_external_contrib.py, reusable_workflows/tests/test_data/repo_list.txt
This change allows comments in the https://github.com/dfinity/repositories-open-to-contributions/blob/master/open-repositories.txt file. When reading the file it ignores the comments.
=> feat(IDX): allow comments in repo list

.github/workflows/internal_vs_external.yml
Switch to `pull_request_target` so workflow doesn't need manual approval.
=> chore(IDX): update trigger

.github/workflows/repo_policies.yml, .github/workflows/repo_policies_ruleset.yml
This needs to be called separately so that other orgs can reuse this workflow.
Reverts dfinity/public-workflows#106
=> Revert "chore(IDX): simplify repo policies workflow"

reusable_workflows/check_membership/check_membership.py, reusable_workflows/tests/test_membership.py
Forgot that other repos still need to use the original bot.
Reverts dfinity/public-workflows#111
=> Revert "chore(IDX): update approved bots list"

.github/workflows/check_external_files.yml
Because we need to check out 2 repositories at once, things can get a little messy.
=> fix(IDX): update python path

.github/workflows/check_external_files.yml
This leaves a comment on the PR if external contributors made a change to files they shouldn't. It makes it a little more explicit in case they don't immediately see the workflow failure.
=> feat(IDX): leave comment if workflow fails

.github/workflows/check_external_files.yml
The problem with `continue-on-error` is that the workflow is marked as green, which is misleading. I want to try something else.
=> fix(IDX): change workflow logic

README.md
This change introduces git flow, so that changes can first be tested on the `develop` branch before releasing to the production workflows.
For context, we previously tried merging directly to main, then creating new releases via tags, but this caused a lot of disruption for developers, as new tags caused old workflows to become "stuck" and needed to be re-triggered.
=> chore(IDX): update README, introduce git flow

.github/workflows/repo_policies.yml
This is also called from the k8s repo, so we need to keep the `workflow_call` trigger.
=> chore(IDX): add workflow_call back

.github/workflows/check_cla_ruleset.yml
There was a permissions issue with running the CLA, so I'm trying to add the token.
=> chore(IDX): add github token to CLA check

reusable_workflows/check_membership/check_membership.py
Temporarily allow 'droid-uexternal' bot to contribute for testing.
=> chore(IDX): allow testing with droid-uexternal user
