dfinity/public-workflows

.github/workflows/check_cla.yml

The workflow isn't getting triggered in the other repo, I will try adding the `pull_request` trigger.

Add pull_request trigger

---

.github/workflows/check_cla.yml

It looks like `merge_group` is required for merge queues.

Add merge_group

---

.github/workflows/check_cla.yml
reusable_workflows/check_membership/check_external_contrib/action.yml
reusable_workflows/check_membership/check_membership/action.yml
reusable_workflows/check_membership/check_membership/check_membership.py
reusable_workflows/tests/test_membership.py

Simplify things by passing them directly as env vars.

Pass in gh_token as env var

---

.github/workflows/check_cla.yml

Still some issues related to forked repos - let's see if this works.

correctly check out repo

---

.github/workflows/check_cla.yml

For some reason the github CLI is having difficulty recognizing the PR number. Trying it a different way.

change close PR

---

.github/workflows/check_cla.yml
.github/workflows/check_cla_dev.yml
.github/workflows/check_cla_ruleset.yml

Not sure if this will work with rulesets, but worth a try.

try reusable workflow

---

.github/workflows/check_cla.yml
.github/workflows/check_cla_ruleset.yml

The merge queue gets stuck, so it looks like this was needed after all.

Add merge group back

---

.github/workflows/check_cla_signed.yml

Moved from: https://github.com/dfinity/cla/pull/404

add workflow to this repo

---

.github/workflows/check_cla_ruleset.yml
README.md

We removed tags as they were unnecessarily complicated and also caused issues with blocking PRs.

refactor(IDX): remove tagging

---

.github/workflows/check_cla.yml

We need to exempt the automation bot to prevent its PRs from getting closed, like here: https://github.com/dfinity/ic/pull/2705

fix(IDX): exempt automation bot from CLA

---

reusable_workflows/check_cla/check_cla_pr.py
reusable_workflows/shared/messages.py
reusable_workflows/tests/test_cla_pr.py

This will make it easier for debugging so we can see which PRs created a CLA issue.

chore(IDX): update cla issue

---

.github/workflows/check_cla.yml

Missed this step when I upgraded everything else.

chore(IDX): upgrade python

---

.github/workflows/repo_policies.yml
reusable_workflows/repo_policies/bot_checks/check_bot_approved_files.py

The error messages still aren't displaying properly. This might require some trial and error.

chore(IDX): fix bot workflow

---

reusable_workflows/check_cla/check_cla_issue.py
reusable_workflows/check_cla/check_cla_pr.py
reusable_workflows/tests/test_cla_issue.py
reusable_workflows/tests/test_cla_pr.py

Small error, will revert so I have more time to look into it.
Reverts dfinity/public-workflows#78

Revert "refactor(IDX): update comment logic"

---

README.md
requirements.txt

This upgrades all packages and in the process removes deprecation warnings that have been showing up in tests.

chore(IDX): upgrade packages

---

.github/workflows/repo_policies.yml

This handles cases where the PR is created from a fork.

chore(IDX): add repo to checkout

---

.github/workflows/check_cla.yml
.github/workflows/check_cla_ruleset.yml
.github/workflows/check_membership.yml
.github/workflows/internal_vs_external.yml

@basvandijk looks like you were referencing reusing an "action" where I was actually reusing a workflow. See docs here: https://docs.github.com/en/actions/sharing-automations/reusing-workflows#example-caller-workflow. I get the two confused all the time too.

feat(IDX): reuse check-membership workflow

---

.github/workflows/check_is_bot.yml
.github/workflows/repo_policies.yml
reusable_workflows/repo_policies/check_bot_approved_files.py
reusable_workflows/repo_policies/check_is_bot.py
reusable_workflows/tests/test_repo_policies.py

This does not change any behavior, but just splits up the existing workflow into two separate steps so that more refactoring can be done later.

chore(IDX): refactor bot checks workflow

---

.github/workflows/internal_vs_external.yml
reusable_workflows/repo_policies/check_external_changes.py
reusable_workflows/tests/test_external_changes.py

Similar to https://github.com/dfinity/public-workflows/pull/142 we can replace the checkout with a github action.

chore(IDX): replace checkout with changed files action

---

.github/workflows/check_cla_ruleset.yml
.github/workflows/check_is_bot.yml
.github/workflows/repo_policies.yml
reusable_workflows/repo_policies/check_bot_approved_files.py
reusable_workflows/repo_policies/check_is_bot.py
reusable_workflows/tests/test_repo_policies.py

Reverts dfinity/public-workflows#144
Didn't test changing multiple files - need to look into this.

Revert "refactor(IDX): replace checkout with github action"

---

.github/workflows/check_is_bot.yml
.github/workflows/repo_policies.yml
reusable_workflows/repo_policies/check_is_bot.py

I needed to revert https://github.com/dfinity/public-workflows/pull/149 for other reasons yesterday, so now I'm adding the changes back in, but breaking them out into separate PRs.
This PR doesn't introduce any new changes, it just fixes the existing issues I found.

chore(IDX): workflow fixes

---

.github/workflows/check_cla_ruleset.yml
.github/workflows/check_is_bot.yml
.github/workflows/repo_policies.yml
reusable_workflows/repo_policies/check_bot_approved_files.py
reusable_workflows/tests/test_repo_policies.py

This contains the same code as in this PR: https://github.com/dfinity/public-workflows/pull/142 - except that I changed how the file list is processes, using whitespace instead of commas to split the list.
Successful PR here: https://github.com/dfinity/test-compliant-repository/pull/17

chore(IDX): replace changed files step with gh action (#155)

---

reusable_workflows/repo_policies/check_external_changes.py

Small fix related to file output handling.

fix(IDX): change file output handling
